# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build_deploy:
  before_script:
    - chmod 600 ${SSH_KEY}
  script: |
    npm ci
    npm run build:apache
    tar cfC - dist/ml-website . | ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEPLOY_HOST} tar xfC - /var/www/mlwebsite/ki
