# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build:       # This job runs in the build stage, which runs first.
  stage: build
  script: |
    npm ci
    npm run build:apache

deploy:
  stage: deploy
  before_script:
    - 'which rsync || ( apt-get update -y && apt-get install -y rsync )'
    - chmod 600 ${SSH_KEY}
    - ls
    - ls /builds/stu210239/ml-website/dist/ml-website
    - ls dist/ml-website/
  script:
    - rsync -rltgoDzvO --delete --progress -e "ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" dist/ml-website/ ${SSH_USER}@${DEPLOY_HOST}:${TARGET_DIR}